/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;
import static oop.utils.Utils.rememberMe;

/**
 *
 * @author proxc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        LogOutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LogoutImgLabel = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        StudentLabel = new javax.swing.JLabel();
        StudentImgLabel = new javax.swing.JLabel();
        TestPanel = new javax.swing.JPanel();
        TestLabel = new javax.swing.JLabel();
        TestImgLabel = new javax.swing.JLabel();
        StatisticPanel = new javax.swing.JPanel();
        StatisticLabel = new javax.swing.JLabel();
        StatisticImgLabel = new javax.swing.JLabel();
        HistoryPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        HistoryImgLabel = new javax.swing.JLabel();
        SettingPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        SettingImgLabel = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NTT");
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(860, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content.setBackground(new java.awt.Color(255, 255, 255));

        LogOutPanel.setBackground(java.awt.SystemColor.controlHighlight);
        LogOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogOutPanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("Log out");

        LogoutImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/download_52px.png"))); // NOI18N

        javax.swing.GroupLayout LogOutPanelLayout = new javax.swing.GroupLayout(LogOutPanel);
        LogOutPanel.setLayout(LogOutPanelLayout);
        LogOutPanelLayout.setHorizontalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutImgLabel)
                    .addComponent(jLabel2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        LogOutPanelLayout.setVerticalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogoutImgLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentPanel.setBackground(java.awt.SystemColor.controlHighlight);
        StudentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudentPanelMousePressed(evt);
            }
        });

        StudentLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StudentLabel.setForeground(new java.awt.Color(45, 118, 232));
        StudentLabel.setText("Student");

        StudentImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_52px.png"))); // NOI18N

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(StudentLabel)
                    .addComponent(StudentImgLabel))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(StudentImgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        TestPanel.setBackground(java.awt.SystemColor.controlHighlight);
        TestPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TestPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TestPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TestPanelMousePressed(evt);
            }
        });

        TestLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TestLabel.setForeground(new java.awt.Color(45, 118, 232));
        TestLabel.setText("Test");

        TestImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/classroom_48px.png"))); // NOI18N

        javax.swing.GroupLayout TestPanelLayout = new javax.swing.GroupLayout(TestPanel);
        TestPanel.setLayout(TestPanelLayout);
        TestPanelLayout.setHorizontalGroup(
            TestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(TestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TestLabel)
                    .addComponent(TestImgLabel))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        TestPanelLayout.setVerticalGroup(
            TestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TestImgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TestLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        StatisticPanel.setBackground(java.awt.SystemColor.controlHighlight);
        StatisticPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StatisticPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatisticPanelMouseExited(evt);
            }
        });

        StatisticLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StatisticLabel.setForeground(new java.awt.Color(45, 118, 232));
        StatisticLabel.setText("Statistics");

        StatisticImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/classroom_48px.png"))); // NOI18N

        javax.swing.GroupLayout StatisticPanelLayout = new javax.swing.GroupLayout(StatisticPanel);
        StatisticPanel.setLayout(StatisticPanelLayout);
        StatisticPanelLayout.setHorizontalGroup(
            StatisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(StatisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(StatisticLabel)
                    .addComponent(StatisticImgLabel))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        StatisticPanelLayout.setVerticalGroup(
            StatisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(StatisticImgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatisticLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        HistoryPanel.setBackground(java.awt.SystemColor.controlHighlight);
        HistoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistoryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistoryPanelMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 232));
        jLabel9.setText("History");

        HistoryImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_64px.png"))); // NOI18N

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoryPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(HistoryImgLabel))
                .addGap(34, 34, 34))
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HistoryImgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        SettingPanel.setBackground(java.awt.SystemColor.controlHighlight);
        SettingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingPanelMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 232));
        jLabel11.setText("Settings");

        SettingImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_48px.png"))); // NOI18N

        javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
        SettingPanel.setLayout(SettingPanelLayout);
        SettingPanelLayout.setHorizontalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(SettingImgLabel))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        SettingPanelLayout.setVerticalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(SettingImgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addComponent(StudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(TestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(StatisticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(SettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(LogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StatisticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 860, 350));

        Header.setBackground(new java.awt.Color(45, 118, 232));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Power up your skill");
        Header.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        Header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EngFlight");
        Header.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jTextField1.setBackground(new java.awt.Color(45, 118, 232));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        Header.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 334, 25));
        Header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 348, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/navigation.png"))); // NOI18N
        Header.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 100));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_20px_1.png"))); // NOI18N
        Header.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void StudentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentPanelMouseEntered
        // TODO add your handling code here:
        setColor(StudentPanel);
    }//GEN-LAST:event_StudentPanelMouseEntered

    private void StudentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentPanelMouseExited
        // TODO add your handling code here:
        resetColor(StudentPanel);
    }//GEN-LAST:event_StudentPanelMouseExited
     
    
    
    
    int xx,xy;
    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);  
    }//GEN-LAST:event_HeaderMouseDragged

    private void TestPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestPanelMouseEntered
        // TODO add your handling code here:
        setColor(TestPanel);
    }//GEN-LAST:event_TestPanelMouseEntered

    private void TestPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestPanelMouseExited
        // TODO add your handling code here:
        resetColor(TestPanel);
    }//GEN-LAST:event_TestPanelMouseExited

    private void StatisticPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticPanelMouseEntered
        // TODO add your handling code here
        setColor(StatisticPanel);
    }//GEN-LAST:event_StatisticPanelMouseEntered

    private void StatisticPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticPanelMouseExited
        // TODO add your handling code here:
        resetColor(StatisticPanel);
    }//GEN-LAST:event_StatisticPanelMouseExited

    private void HistoryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryPanelMouseEntered
        // TODO add your handling code here:
        setColor(HistoryPanel);
    }//GEN-LAST:event_HistoryPanelMouseEntered

    private void HistoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryPanelMouseExited
        // TODO add your handling code here:
        resetColor(HistoryPanel);
        
    }//GEN-LAST:event_HistoryPanelMouseExited

    private void SettingPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingPanelMouseEntered
        // TODO add your handling code here:
        setColor(SettingPanel);
    }//GEN-LAST:event_SettingPanelMouseEntered

    private void SettingPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingPanelMouseExited
        // TODO add your handling code here:
        resetColor(SettingPanel);
    }//GEN-LAST:event_SettingPanelMouseExited

    private void LogOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelMouseEntered
        // TODO add your handling code here:
        setColor(LogOutPanel);
    }//GEN-LAST:event_LogOutPanelMouseEntered

    private void LogOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelMouseExited
        // TODO add your handling code here:
        resetColor(LogOutPanel);
    }//GEN-LAST:event_LogOutPanelMouseExited

    private void StudentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentPanelMousePressed
        // TODO add your handling code here:
        new Home_Data().show();
    }//GEN-LAST:event_StudentPanelMousePressed

    private void TestPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestPanelMousePressed
        // TODO add your handling code here:
        //just a sample.
        new Students().show();
    }//GEN-LAST:event_TestPanelMousePressed

    private void LogOutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelMousePressed
        rememberMe("");
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_LogOutPanelMousePressed
 public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HistoryImgLabel;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JPanel LogOutPanel;
    private javax.swing.JLabel LogoutImgLabel;
    private javax.swing.JLabel SettingImgLabel;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JLabel StatisticImgLabel;
    private javax.swing.JLabel StatisticLabel;
    private javax.swing.JPanel StatisticPanel;
    private javax.swing.JLabel StudentImgLabel;
    private javax.swing.JLabel StudentLabel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JLabel TestImgLabel;
    private javax.swing.JLabel TestLabel;
    private javax.swing.JPanel TestPanel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
